name: mdmerge
description: Use placeholders in markdown files to include other markdown, text or source files.
version: 1.0.0+1
repository: https://github.com/xErik/mdmerge
issues: https://github.com/xErik/mdmerge/issues

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
